### Basic Statistics - 2

In [1]:
"""
Problem Statement : Hospital Patient Data Analysis
Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount.
You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, 
and there are multiple rows for the same patient due to follow-ups.

Tasks:
1.	Load the patient dataset and show summary with info().
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
4.	Use groupby to find total bill amount per department.
5.	Remove duplicate patient records based on PatientID.
6.	Fill missing BillAmount values with the mean bill amount.
7.	Merge the billing dataset with patient dataset on PatientID.
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

Expected Outcome:
•	Final cleaned dataset with accurate billing info.
•	All missing values handled, merged dataset across PatientID.
•	Ability to perform further analytics on department-wise revenue or doctor performance.

"""
import pandas as pd 


# loading files to the enviroment
df1 = pd.read_csv("Patient_Data.csv")

# Loading billing dataset 
df2 = pd.read_csv("Billing_Data.csv")

# I am going to work on a copy to keep original intact
data_patient = df1.copy()


# 1.Load the patient dataset and show summary with info().
print(data_patient.info())


# 2.Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
# 3.Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
billing_patient = data_patient[['PatientID', 'Department', 'Doctor', 'BillAmount']]
print(billing_patient)

# 4.Use groupby to find total bill amount per department.
bill_amt_per_department = billing_patient.groupby("Department")["BillAmount"].sum().reset_index()
print(bill_amt_per_department)

# 5.Remove duplicate patient records based on PatientID.
print("\n<--------- Removing Duplicates From The Dataset According To The PatientID. -------> \n")
billing_patient.drop_duplicates(subset="PatientID",inplace=True)
print(billing_patient)

print("\n<------ Loking for how many empty cell are in different columns--------> \n")
print(billing_patient.isnull().sum())

# 6.Fill missing BillAmount values with the mean bill amount.
print("\n <------ finding the mean of the billmount to fill the missing values------>\n")
value = billing_patient["BillAmount"].mean()
print(f"The mean value is :{value}")

print("\n<--------Filling the missing values with the mean value of the bill amount -------->\n")
billing_patient["BillAmount"] = billing_patient["BillAmount"].fillna(value)
print(billing_patient)

# 7.Merge the billing dataset with patient dataset on PatientID.
print("\n<-------Merging------>\n")
merged_dataset = pd.merge(billing_patient,df2,on="PatientID")
print(merged_dataset)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes
None
   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0
    Department  BillAmount
0   Cardiology     16200.0
1  Dermatology         0.0
2    Neurology         0.0
3  Orthopedics      7500.0

<--------- Removing Duplicates From The Dataset According To The PatientID. ------->

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

<------ Loking for how many empty cell are in different columns-------->

PatientID     0
Department    0
Doctor        0
BillAmount    2
dtype: int64

 <------ finding the mean of the billmount to fill the missing values------>

The mean value is :6233.333333333333

<--------Filling the missing values with the mean value of the bill amount -------->

   PatientID   Department     Doctor   BillAmount
0        101   Cardiology  Dr. Smith  5000.000000
1        102    Neurology   Dr. John  6233.333333
2        103  Orthopedics    Dr. Lee  7500.000000
3        104   Cardiology  Dr. Smith  6200.000000
4        105  Dermatology   Dr. Rose  6233.333333

<-------Merging------>

   PatientID   Department     Doctor   BillAmount  InsuranceCovered  \
0        101   Cardiology  Dr. Smith  5000.000000              2000
1        102    Neurology   Dr. John  6233.333333              1500
2        103  Orthopedics    Dr. Lee  7500.000000              2500
3        104   Cardiology  Dr. Smith  6200.000000              3000
4        105  Dermatology   Dr. Rose  6233.333333              1000

   FinalAmount
0         3000
1         3500
2         5000
3         3200
4         4000

C:\Users\mdrud\AppData\Local\Temp\ipykernel_21632\45950607.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  billing_patient.drop_duplicates(subset="PatientID",inplace=True)
C:\Users\mdrud\AppData\Local\Temp\ipykernel_21632\45950607.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  billing_patient["BillAmount"] = billing_patient["BillAmount"].fillna(value)

In [4]:
merged_dataset

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Neurology,Dr. John,6233.333333,1500,3500
2,103,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Dermatology,Dr. Rose,6233.333333,1000,4000

In [2]:
# 8.Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
# 9. Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
# Lets say an additional dataframe is given by 
patient_data_new_week = {
    "PatientID":[106,107,108,109,110],
    "Department":["Cardiology","Neurology","Orthopedics"," Cardiology","Dermatology "],
    "Doctor":["Mona","Suresh","Purnima","Vairava","Niranjan"],
    "BillAmount":[2000,3000,4000,5000, 6000]
}

patient_new_data = pd.DataFrame(patient_data_new_week)
print(patient_new_data)

# Lets create new billing that has been doene for these patients 
new_billings_week = {
    "PatientID":[106,107,108,109,110],
    "InsuranceCovered":[1000,1000,2000,2000,3000],
    "FinalAmount":[1000,2000,2000,3000,3000]
}
new_billing = pd.DataFrame(new_billings_week)
# Merging the two data frame first using the patientid

print("\n<---------Our new columns according to the neww weekday--------->\n")
merging_new = pd.merge(patient_new_data,new_billing, on="PatientID")
print(merging_new)

   PatientID    Department    Doctor  BillAmount
0        106    Cardiology      Mona        2000
1        107     Neurology    Suresh        3000
2        108   Orthopedics   Purnima        4000
3        109    Cardiology   Vairava        5000
4        110  Dermatology   Niranjan        6000

<---------Our new columns according to the neww weekday--------->

   PatientID    Department    Doctor  BillAmount  InsuranceCovered  \
0        106    Cardiology      Mona        2000              1000
1        107     Neurology    Suresh        3000              1000
2        108   Orthopedics   Purnima        4000              2000
3        109    Cardiology   Vairava        5000              2000
4        110  Dermatology   Niranjan        6000              3000

   FinalAmount
0         1000
1         2000
2         2000
3         3000
4         3000

In [3]:
# The Final output Where there is no vacant place and no duplicates is given buy 
df_with_new_patients = pd.concat([merged_dataset, merging_new], axis=0, ignore_index=True)
print(df_with_new_patients)

   PatientID    Department     Doctor   BillAmount  InsuranceCovered  \
0        101    Cardiology  Dr. Smith  5000.000000              2000
1        102     Neurology   Dr. John  6233.333333              1500
2        103   Orthopedics    Dr. Lee  7500.000000              2500
3        104    Cardiology  Dr. Smith  6200.000000              3000
4        105   Dermatology   Dr. Rose  6233.333333              1000
5        106    Cardiology       Mona  2000.000000              1000
6        107     Neurology     Suresh  3000.000000              1000
7        108   Orthopedics    Purnima  4000.000000              2000
8        109    Cardiology    Vairava  5000.000000              2000
9        110  Dermatology    Niranjan  6000.000000              3000

   FinalAmount
0         3000
1         3500
2         5000
3         3200
4         4000
5         1000
6         2000
7         2000
8         3000
9         3000

In [5]:
df_with_new_patients

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Neurology,Dr. John,6233.333333,1500,3500
2,103,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Dermatology,Dr. Rose,6233.333333,1000,4000
5,106,Cardiology,Mona,2000.000000,1000,1000
6,107,Neurology,Suresh,3000.000000,1000,2000
7,108,Orthopedics,Purnima,4000.000000,2000,2000
8,109,Cardiology,Vairava,5000.000000,2000,3000
9,110,Dermatology,Niranjan,6000.000000,3000,3000